//
//package org.leibnizcenter.cfg.earleyparser.event;
//
//
//import org.leibnizcenter.cfg.earleyparser.parse.Parse;
//
//
///**
// * An event generated by an {@link EarleyParser Earley parser} having to do
// * with a completed {@link Parse parse}.
// *
// */
//@SuppressWarnings("unused")
//public class ParseEvent extends ParserEvent {
//    private static final long serialVersionUID = 1L;
//    public Parse parse;
//
//    /**
//     * Creates a new parse event for the given parse. The string index used
//     * will be the size of the {@link Parse#getTokens() parse's tokens}.
//     *
//     * @param parse The parse in question.
//     */
//    public ParseEvent(Parse parse) {
//        this(parse.tokens.size(), parse);
//    }
//
//    /**
//     * Creates a new event concerning the specified parse.
//     *
//     * @param parse The parse in question.
//     */
//    @SuppressWarnings("WeakerAccess")
//    public ParseEvent(int index, Parse parse) {
//        super(index);
//        this.parse = parse;
//    }
//
//    /**
//     * Gets the parse associated with this event.
//     *
//     * @return The parse that was specified when this event was created.
//     */
//    public Parse getParse() {
//        return parse;
//    }
//}
