//
//package org.leibnizcenter.cfg.earleyparser.event;
//
//
//import org.leibnizcenter.cfg.earleyparser.exception.ParseException;
//import org.leibnizcenter.cfg.earleyparser.parse.Parse;
//
///**
// * An event triggered when an error occurs during parsing.
// *
// * @see ParserListener#parseError(ParseErrorEvent)
// */
//@SuppressWarnings("unused")
//public class ParseErrorEvent extends ParseEvent {
//    private static final long serialVersionUID = 1L;
//
//    public ParseException cause;
//
//    /**
//     * An event generated by an error during parsing at a specified index.
//     *
//     * @param cause The exception that caused this error to be generated.
//     * @see ParseEvent#ParseEvent(int, Parse)
//     */
//    public ParseErrorEvent(int index, Parse parse, ParseException cause) {
//        super(index, parse);
//        this.cause = cause;
//    }
//
//    /**
//     * Gets the exception that caused this error event to be generated.
//     *
//     * @return The exception that was specified when this event was created.
//     */
//    public ParseException getCause() {
//        return cause;
//    }
//
//}
