//
//package org.leibnizcenter.cfg.earleyparser.event;
//
//
//import org.leibnizcenter.cfg.category.Category;
//import org.leibnizcenter.cfg.earleyparser.chart.State;
//import org.leibnizcenter.cfg.earleyparser.parse.Chart;
//
///**
// * An event generated when an {@link State State} is added to a
// * {@link Chart chart} in {@link EarleyParser#parse(Iterable, Category)
// * Earley parsing}.
// *
// * @see Chart
// * @see EarleyParser
// * @see ParserListener
// */
//public class StateEvent extends ParserEvent {
//    public final State State;
//
//    /**
//     * Creates a new State event generated by the specified parser for the
//     * given State at the specified index.
//     *
//     * @param State The State whose addition generated this event.
//     * @param index The string index where the event was generated.
//     * @see ParseEvent(EarleyParser, int)
//     */
//    public StateEvent(int index, State State) {
//        super(index);
//        this.State = State;
//    }
//
//    /**
//     * Gets the State whose addition generated this event.
//     *
//     * @return The State specified when this event was created.
//     */
//    public State getState() {
//        return State;
//    }
//}
